export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";


export const CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const CART_DATA_SUCCESS = "CART_DATA_SUCCESS";
export const CART_DATA_FAILURE = "CART_DATA_FAILURE";



export const CART_DATA_GET_REQUEST = "CART_DATA_GET_REQUEST";
export const CART_DATA_GET_SUCCESS = "CART_DATA_GET_SUCCESS";
export const CART_DATA_GET_FAILURE = "CART_DATA_GET_FAILURE";